# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.

theme = "blowfish"
baseURL = "https://n9o.xyz/"
defaultContentLanguage = "en"
disableLanguages = ['pt-pt']

enableRobotsTXT = true
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true

googleAnalytics = "G-R94R4YKFEC"

[pagination]
  pagerSize = 27

[params.author]
  name = "Vaishnav Baraskar"
  image = "img/bw_avatar.png"
  headline = "Penetration Tester @ Freelancer"
  bio = "Penetration Tester @ Freelancer"
  links = [
    #{ email = "baraskarvaishnav86@gmail.com" },
    { linkedin = "https://www.linkedin.com/in/vaishnav-baraskar-b99029289/" },
    { github = "https://github.com/vaishnavbaraskar" },
    #{ medium = "https://medium.com/@nunocoracao" },
    #{ hackernews = "https://news.ycombinator.com/user?id=nunocoracao"},
    #{ mastodon = "https://masto.ai/@nunocoracao" },
    { instagram = "https://instagram.com/vaishnvbaraskar" },
    #{ reddit = "https://reddit.com/user/nunoheart" },
    #{ telegram = "https://t.me/nunocoracao" },
    #{ music = "/music" },
  ]


[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 1
  includeNewer = true
  toLower = true

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 10

    [[related.indices]]
        name = "date"
        weight = 0

    [[related.indices]]
      applyFilter = true
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10

